#!/usr/bin/env python
import os
import sys

import click

root = os.path.realpath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(root)


@click.group()
def cli():
    pass


@click.command()
def run():
    from thavalon import app
    from thavalon.helpers import env_is_dev

    port = int(os.environ.get('PORT', '8080'))
    with app.app_context():
        app.run(host='0.0.0.0', port=port, debug=env_is_dev())


@click.command()
def format():
    from yapf import FormatFiles
    from yapf.yapflib import file_resources
    files = file_resources.GetCommandLineFiles([os.path.join(root, 'thavalon')], True, None)
    FormatFiles(files, None, parallel=True, in_place=True, verbose=True)


cli.add_command(run)
cli.add_command(format)


if __name__ == '__main__':
    cli()